name: Ecology Knowledge-Guided Machine Learning
title: Ecology Knowledge-Guided Machine Learning
description: The Next Frontier in Ecological Modeling
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
